CREATE TABLE CONDOMINIO(
    id_condominio NUMBER NOT NULL,
    CONDOMINIIO   VARCHAR2(30),
    sindico       VARCHAR2(30),
    senha         VARCHAR2(10)
);

CREATE SEQUENCE administor.seq_condominio INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 NOCACHE NOCYCLE;-- CRIAR UMA SEQUENCE


CREATE TABLE REUNIAO(
ID_REUNIAO  NUMBER NOT NULL,
NOME        VARCHAR2(30),
ONDE        VARCHAR2(50),
DIA         VARCHAR2(10),
HORARIO     VARCHAR2(32)
);

CREATE SEQUENCE administor.seq_reuniao INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 NOCACHE NOCYCLE;-- CRIAR UMA SEQUENCE

select * from reuniao;