CREATE TABLE CONDOMINIO(
    id_condominio NUMBER NOT NULL,
    CONDOMINIIO   VARCHAR2(30),
    sindico       VARCHAR2(30),
    senha         VARCHAR2(10)
);

CREATE SEQUENCE administor.seq_condominio INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 NOCACHE NOCYCLE;-- CRIAR UMA SEQUENCE


CREATE TABLE REUNIAO(
ID_REUNIAO  NUMBER NOT NULL,
NOME        VARCHAR2(30),
ONDE        VARCHAR2(50),
DIA         VARCHAR2(10),
HORARIO     VARCHAR2(32)
);
ALTER TABLE REUNIAO ADD CONSTRAINT PK_ID_REUNIAO PRIMARY KEY(ID_REUNIAO);
CREATE SEQUENCE administor.seq_reuniao INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 NOCACHE NOCYCLE;-- CRIAR UMA SEQUENCE

CREATE TABLE PARTICIPANTE(
ID_PARTICIPANTE NUMBER NOT NULL,
ID_REUNIAO NUMBER NOT NULL,
NOME            VARCHAR2(30),
CELULAR         VARCHAR2(15)

);

ALTER TABLE PARTICIPANTE ADD CONSTRAINT FK_ID_REUNIAO FOREIGN KEY (ID_REUNIAO) REFERENCES REUNIAO(ID_REUNIAO);
CREATE SEQUENCE administor.SEQ_PARTICIPANTE INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 NOCACHE NOCYCLE;-- CRIAR UMA SEQUENCE